#!/bin/sh
# generate tag file for lookupfile plugin
#!/bin/sh
# generate tag file for lookupfile plugin
# echo -e "!_TAG_FILE_SORTEDt2t/2=foldcase/"> filenametags
# gfind . -not -regex '.*.(png|gif|swp|jpg|DS_Store)' ! -path "*svn*" ! -path "*templates*" -type f -printf "%ft%pt1n" | sort -f >> filenametags


#!/bin/sh
# generate tag file for lookupfile plugin
export LC_ALL=UTF-8
echo -e "!_TAG_FILE_SORTED\t2\t/2=foldcase/" > filenametags
gfind . -not -regex '.*\.\(png\|gif\)' -type f -printf "%f\t%p\t1\n" | sort -f >> filenametags 
